source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SGBackgroundView_Example', :exclusive => true do
  pod "SGBackgroundView", :path => "../"
end

target 'SGBackgroundView_Tests', :exclusive => true do
  pod "SGBackgroundView", :path => "../"

  
end
